name: m-sandbox-01
recipe: drupal9
config:
  composer_version: '2.2.12'
  config:
    php: .lando/php.ini
  database: mysql:5.7
  drush: true
  php: '8.1'
  via: apache:2.4
  webroot: web
  xdebug: false
services:
  appserver:
    build_as_root:
      - apt-get update -y
      - apt-get install -y vim
      - chmod -R 777 /app/private
      - chmod -R 777 /app/web/sites/default/files
    overrides:
      volumes:
        - "/Volumes/MSD01/Sites/m-sandbox-01/public:/app/web/sites/default/files"
        - "/Volumes/MSD01/Sites/m-sandbox-01/private:/app/private"
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: false
  pma:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node
    ssl:  true
    build:
      - npm install
    globals:
      grunt-cli: latest
      gulp-cli: latest
      npm: latest
      webpack: latest
      yarn: latest
    command: cd /app/web/themes/contrib/mbgna_dxpr && node_modules/.bin/grunt watch
  proxy:
    node:
      - bs.m-sandbox-01.lndo.site:3000
tooling:
  drush:
    service: appserver
  grunt:
    service: node
  gulp:
    service: node
  node:
    service: appserver
  npm:
    service: node
  webpack:
    service: node
  yarn:
    service: node
