# Change "00" to an identifying character set.
name: m-sandbox-00
recipe: drupal9
config:
  php: '8.1'
  composer_version: '2.2.12'
  via: apache:2.4
  webroot: web
  database: mysql:5.7
  drush: true
  xdebug: false
  config:
    php: .lando/php.ini
services:
  appserver:
    build_as_root:
      - composer install --ignore-platform-reqs
      - chmod -R 777 /app/private
      - chmod -R 777 /app/web/sites/default/files
      # Vim
      - apt-get update
      - apt-get install -y vim
    overrides:
      volumes:
        # Change "DRIVE" to the drive name and 
        # change "PROJECT" to the website/project/directory name.
        - "/Volumes/MSD01/Sites/m-sandbox-00/public:/app/web/sites/default/files"
        - "/Volumes/MSD01/Sites/m-sandbox-00/private:/app/private"
  mailhog:
    type: mailhog
    portforward: false
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
  node:
    type: node
    build:
      - npm install
    globals:
      gulp-cli: latest
      webpack: latest
      npm: latest
tooling:
  npm:
    service: node
  node:
    service: appserver
  gulp:
    service: node
  webpack:
    service: node
  yarn:
    service: node
  drush:
    service: appserver